In [87]:
import pandas as pd

In [88]:
busan = pd.read_csv('./csv/BUSAN_ALL.csv', encoding='utf-8')

In [5]:
ulsan = pd.read_csv('./csv/ULSAN_ALL.csv', encoding='euc-kr')

In [6]:
incheon = pd.read_csv('./csv/INCHEON_ALL.csv', encoding='euc-kr')

In [89]:
busan = busan.rename(columns={'Unnamed: 0':'GUGUN'})
busan

   GUGUN     인구수     교통  학교수    1근린   2근린     행사수         치안율  아파트평당가격
0    강서구  133231   83.0   34    4.0  91.0   350.0   74.393723    900.0
1    금정구  245670   55.0   48   17.0  37.0  1234.0   85.841343    900.0
2    기장군  167231   40.0   33    7.0  83.0   501.0   84.019095    725.0
3     남구  283267   69.0   46   19.0  72.0  4343.0   81.613035    850.0
4     동구   89692   24.0   19   20.0   5.0   521.0   85.595960    500.0
5    동래구  271004   71.0   49   41.0  50.0  1603.0   82.966828   1000.0
6   부산진구  362296   75.0   68  117.0  40.0  2048.0   74.354362    900.0
7     북구  294030   75.0   52   23.0  75.0  1021.0   87.089070    750.0
8    사상구  225751   78.0   37   26.0  46.0   719.0   88.089766    700.0
9    사하구  327956  104.0   57   31.0  78.0  1163.0   79.586089    500.0
10    서구  111044   25.0   23   17.0  29.0   596.0   85.512266    800.0
11   수영구  178484   22.0   20   33.0  17.0  1825.0   81.613035   1100.0
12   연제구  210393   33.0   29   22.0  25.0  1393.0   77.875998    850.0
13   영도구  119602   25.0   30    5.0  33.0   568.0  110.191496    500.0
14    중구   44223   25.0    9   23.0  12.0   246.0   79.485725    500.0
15  해운대구  411445   48.0   66   46.0  73.0  3822.0   82.815341   1000.0

In [90]:
busan=busan.set_index('GUGUN')

In [91]:
busan.index

Index(['강서구', '금정구', '기장군', '남구', '동구', '동래구', '부산진구', '북구', '사상구', '사하구',
       '서구', '수영구', '연제구', '영도구', '중구', '해운대구'],
      dtype='object', name='GUGUN')

In [92]:
di=dict()

for i in range(len(busan.index)):
    di[busan.index[i]]='부산_'+busan.index[i]
    
di

{'강서구': '부산_강서구',
 '금정구': '부산_금정구',
 '기장군': '부산_기장군',
 '남구': '부산_남구',
 '동구': '부산_동구',
 '동래구': '부산_동래구',
 '부산진구': '부산_부산진구',
 '북구': '부산_북구',
 '사상구': '부산_사상구',
 '사하구': '부산_사하구',
 '서구': '부산_서구',
 '수영구': '부산_수영구',
 '연제구': '부산_연제구',
 '영도구': '부산_영도구',
 '중구': '부산_중구',
 '해운대구': '부산_해운대구'}

In [93]:
for i in range(len(busan.index)):
    busan.rename(index=di, inplace=True)
busan

            인구수     교통  학교수    1근린   2근린     행사수         치안율  아파트평당가격
GUGUN
부산_강서구   133231   83.0   34    4.0  91.0   350.0   74.393723    900.0
부산_금정구   245670   55.0   48   17.0  37.0  1234.0   85.841343    900.0
부산_기장군   167231   40.0   33    7.0  83.0   501.0   84.019095    725.0
부산_남구    283267   69.0   46   19.0  72.0  4343.0   81.613035    850.0
부산_동구     89692   24.0   19   20.0   5.0   521.0   85.595960    500.0
부산_동래구   271004   71.0   49   41.0  50.0  1603.0   82.966828   1000.0
부산_부산진구  362296   75.0   68  117.0  40.0  2048.0   74.354362    900.0
부산_북구    294030   75.0   52   23.0  75.0  1021.0   87.089070    750.0
부산_사상구   225751   78.0   37   26.0  46.0   719.0   88.089766    700.0
부산_사하구   327956  104.0   57   31.0  78.0  1163.0   79.586089    500.0
부산_서구    111044   25.0   23   17.0  29.0   596.0   85.512266    800.0
부산_수영구   178484   22.0   20   33.0  17.0  1825.0   81.613035   1100.0
부산_연제구   210393   33.0   29   22.0  25.0  1393.0   77.875998    850.0
부산_영도구   119602   25.0   30    5.0  33.0   568.0  110.191496    500.0
부산_중구     44223   25.0    9   23.0  12.0   246.0   79.485725    500.0
부산_해운대구  411445   48.0   66   46.0  73.0  3822.0   82.815341   1000.0

In [32]:
ulsan=ulsan.set_index('GUGUN')

In [36]:
ulsan.index

Index(['남구', '동구', '북구', '울주군', '중구'], dtype='object', name='GUGUN')

In [60]:
di=dict()

for i in range(len(ulsan.index)):
    di[ulsan.index[i]]='울산_'+ulsan.index[i]
    
di

{'남구': '울산_남구', '동구': '울산_동구', '북구': '울산_북구', '울주군': '울산_울주군', '중구': '울산_중구'}

In [61]:
for i in range(len(ulsan.index)):
    ulsan.rename(index=di, inplace=True)
ulsan

,백화점수,행사수,병원수,도서관수,시장수,공원수,인구수,아파트평당가격,치안율,학교수,교통수
GUGUN,,,,,,,,,,,
울산_남구,3.0,189,147,37.0,9.0,108.0,336914.0,924.0,84.731887,61,135
울산_동구,1.0,23,25,5.0,7.0,73.0,169673.0,726.0,81.612843,34,208
울산_북구,0.0,130,22,7.0,2.0,52.0,207284.0,710.0,78.224456,44,183
울산_울주군,0.0,21,14,14.0,7.0,0.0,228528.0,709.0,81.602084,57,203
울산_중구,0.0,30,32,26.0,17.0,116.0,237012.0,883.0,82.320442,41,64

In [64]:
incheon=incheon.rename(columns={'Unnamed: 0':'GUGUN'})

In [67]:
incheon=incheon.set_index('GUGUN')

In [68]:
incheon.index

Index(['강화군', '계양구', '남동구', '동구', '미추홀구', '부평구', '서구', '연수구', '옹진군', '중구'], dtype='object', name='GUGUN')

In [69]:
di=dict()

for i in range(len(incheon.index)):
    di[incheon.index[i]]='인천_'+incheon.index[i]
    
di

{'강화군': '인천_강화군',
 '계양구': '인천_계양구',
 '남동구': '인천_남동구',
 '동구': '인천_동구',
 '미추홀구': '인천_미추홀구',
 '부평구': '인천_부평구',
 '서구': '인천_서구',
 '연수구': '인천_연수구',
 '옹진군': '인천_옹진군',
 '중구': '인천_중구'}

In [70]:
for i in range(len(incheon.index)):
    incheon.rename(index=di, inplace=True)
incheon

,백화점수,행사수,병원수,도서관수,시장수,공원수,인구수,아파트평당가격,치안율,학교수,역명,주차장수,버스수,교통수
GUGUN,,,,,,,,,,,,,,
인천_강화군,0.0,4.0,1.0,2.0,3.0,3.0,102795.0,385.0,86.144578,38.0,0.0,0.0,37.0,37.0
인천_계양구,0.0,7.0,21.0,4.0,3.0,22.0,434104.0,812.0,89.545341,52.0,7.0,4.0,140.0,151.0
인천_남동구,0.0,29.0,72.0,4.0,7.0,49.0,768394.0,925.0,81.554029,76.0,10.0,6.0,190.0,206.0
인천_동구,0.0,4.0,2.0,1.0,7.0,4.0,94559.0,696.0,81.554029,14.0,0.0,1.0,14.0,15.0
인천_미추홀구,1.0,0.0,20.0,13.0,21.0,45.0,607867.0,826.0,80.248800,50.0,4.0,2.0,116.0,122.0
인천_부평구,2.0,19.0,50.0,36.0,6.0,0.0,744602.0,974.0,81.597092,82.0,6.0,4.0,359.0,369.0
인천_서구,0.0,5.0,35.0,69.0,6.0,109.0,771003.0,983.0,82.800745,84.0,17.0,0.0,729.0,746.0
인천_연수구,1.0,31.0,31.0,13.0,2.0,0.0,501760.0,1273.0,88.120343,61.0,12.0,6.0,449.0,467.0
인천_옹진군,0.0,1.0,0.0,5.0,0.0,0.0,32560.0,0.0,83.294787,16.0,0.0,0.0,0.0,0.0
인천_중구,0.0,29.0,8.0,16.0,3.0,4.0,196155.0,853.0,75.479819,35.0,0.0,12.0,307.0,319.0

In [71]:
busan

,버정수,치안율,지하철역수,공원수,은행수,유치원수,마트수,약국수,학교수,공공기관수,...,문화시설수,아파트평당가격,행사수,병원수,elementary_cnt,middle_cnt,high_cnt,department_cnt,library_cnt,market_cnt
GUGUN,,,,,,,,,,,,,,,,,,,,,
부산_강서구,64.0,74.393723,3.0,72.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1.0,900.0,350.0,1.0,17,11,6,0.0,19.0,3
부산_금정구,42.0,85.841343,9.0,36.0,0.0,1.0,1.0,0.0,2.0,1.0,...,1.0,900.0,1234.0,8.0,22,12,14,1.0,1.0,8
부산_기장군,24.0,84.019095,2.0,83.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.0,725.0,501.0,4.0,21,7,5,0.0,0.0,3
부산_남구,54.0,81.613035,6.0,41.0,0.0,1.0,1.0,0.0,3.0,1.0,...,1.0,850.0,4343.0,7.0,18,13,15,0.0,31.0,12
부산_동구,15.0,85.595960,5.0,4.0,2.0,1.0,0.0,1.0,0.0,1.0,...,2.0,500.0,521.0,8.0,7,6,6,1.0,1.0,11
부산_동래구,56.0,82.966828,11.0,48.0,0.0,5.0,1.0,3.0,1.0,1.0,...,NaN,1000.0,1603.0,25.0,22,14,13,1.0,2.0,15
부산_부산진구,62.0,74.354362,10.0,31.0,5.0,2.0,3.0,3.0,2.0,1.0,...,1.0,900.0,2048.0,80.0,32,18,18,4.0,9.0,33
부산_북구,43.0,87.089070,13.0,72.0,0.0,1.0,0.0,0.0,1.0,1.0,...,2.0,750.0,1021.0,16.0,27,16,9,0.0,3.0,7
부산_사상구,51.0,88.089766,7.0,32.0,2.0,0.0,1.0,2.0,3.0,1.0,...,1.0,700.0,719.0,7.0,21,10,6,0.0,14.0,19
부산_사하구,69.0,79.586089,12.0,60.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,500.0,1163.0,16.0,27,16,14,0.0,18.0,15
부산_서구,17.0,85.512266,3.0,13.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.0,800.0,596.0,8.0,11,7,5,0.0,16.0,9
부산_수영구,10.0,81.613035,7.0,14.0,2.0,1.0,1.0,0.0,0.0,1.0,...,1.0,1100.0,1825.0,13.0,10,6,4,0.0,3.0,20
부산_연제구,18.0,77.875998,8.0,20.0,1.0,1.0,3.0,0.0,0.0,3.0,...,1.0,850.0,1393.0,12.0,16,8,5,0.0,5.0,10
부산_영도구,19.0,110.191496,0.0,15.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,500.0,568.0,2.0,14,9,7,0.0,18.0,3
부산_중구,7.0,79.485725,3.0,5.0,1.0,0.0,0.0,2.0,0.0,0.0,...,2.0,500.0,246.0,3.0,4,1,4,2.0,7.0,18
부산_해운대구,21.0,82.815341,10.0,69.0,2.0,0.0,3.0,3.0,0.0,1.0,...,4.0,1000.0,3822.0,30.0,33,19,14,3.0,4.0,13