In [68]:
import pandas as pd

In [69]:
park = pd.read_csv('./csv/park/incheon_park.csv', encoding='euc-kr')

In [70]:
print(park)

            관리번호   공원명   공원구분               소재지도로명주소  \
0    28710-00003  관청공원   근린공원                    NaN
1    28710-00004  전등공원   역사공원                    NaN
2    28710-00005  내가공원   근린공원                    NaN
3    28710-00007  유아공원  어린이공원  인천광역시 강화군 강화읍 동문안길 15
4    28710-00009  5호공원  어린이공원                    NaN
..           ...   ...    ...                    ...
639  28110-00080    7호   근린공원                    NaN
640  28110-00081    8호   근린공원                    NaN
641  28110-00082    1호  어린이공원                    NaN
642  28110-00083    1호    소공원                    NaN
643  28110-00084    2호    소공원                    NaN

                      소재지지번주소             위도              경도    공원면적  \
0      인천광역시 강화군 강화읍 관청리 산8-1  37.7468034370  126.4916833650  145124
1       인천광역시 강화군 길상면 온수리 산42      37.632824  126.4868582083  143607
2    인천광역시 강화군 내가면 고천리 산109-2      37.734243      126.422700   45000
3     인천광역시 강화군 강화읍 관청리 486-1  37.7473662241  126.4866997714    1769
4        인천광역시 강화군 강화읍 관청리 15  37.7520182546      126.489721    1773
..                        ...            ...             ...     ...
639          인천광역시 중구 운북동 산64     37.4970537     126.5338519   18301
640        인천광역시 중구 운북동 산90-4     37.4970537     126.5338519   65176
641        인천광역시 중구 운북동 339-4     37.4970537     126.5338519    1519
642        인천광역시 중구 운북동 194-3     37.4970537     126.5338519    8120
643          인천광역시 중구 운북동 336     37.4970537     126.5338519    2585

    공원보유시설(운동시설)                   공원보유시설(유희시설) 공원보유시설(편익시설) 공원보유시설(교양시설)  \
0            NaN                            NaN          NaN          NaN
1            NaN                            NaN          NaN          NaN
2            NaN                            NaN          NaN          NaN
3            NaN                            NaN          NaN          NaN
4            NaN                            NaN          NaN          NaN
..           ...                            ...          ...          ...
639          NaN                            NaN          NaN          NaN
640   풋살장, 배드민턴장                            NaN          NaN          NaN
641          NaN  조합놀이대, 그네, 회전놀이기구, 흔들놀이기구, 철봉          NaN          NaN
642          NaN                            NaN          NaN          NaN
643          NaN                            NaN          NaN          NaN

    공원보유시설(기타시설)       지정고시일       관리기관명          전화번호     데이터기준일자
0            NaN  1972-08-23  인천광역시 강화군청  032-930-3876  2019-09-20
1            NaN  1974-05-16  인천광역시 강화군청  032-930-3876  2019-09-20
2            NaN  1974-05-16  인천광역시 강화군청  032-930-3876  2019-09-20
3            NaN  1979-04-20  인천광역시 강화군청  032-930-3876  2019-09-20
4            NaN  1988-02-20  인천광역시 강화군청  032-930-3876  2019-09-20
..           ...         ...         ...           ...         ...
639          NaN  2006-10-31   인천광역시 중구청  032-760-7778  2019-05-31
640      공원관리사무실  2006-10-31   인천광역시 중구청  032-760-7778  2019-05-31
641          NaN  2006-10-31   인천광역시 중구청  032-760-7778  2019-05-31
642          NaN  2008-06-03   인천광역시 중구청  032-760-7778  2019-05-31
643          NaN  2008-06-03   인천광역시 중구청  032-760-7778  2019-05-31

[644 rows x 17 columns]

In [71]:
park.head()

,관리번호,공원명,공원구분,소재지도로명주소,소재지지번주소,위도,경도,공원면적,공원보유시설(운동시설),공원보유시설(유희시설),공원보유시설(편익시설),공원보유시설(교양시설),공원보유시설(기타시설),지정고시일,관리기관명,전화번호,데이터기준일자
0,28710-00003,관청공원,근린공원,NaN,인천광역시 강화군 강화읍 관청리 산8-1,37.7468034370,126.4916833650,145124,NaN,NaN,NaN,NaN,NaN,1972-08-23,인천광역시 강화군청,032-930-3876,2019-09-20
1,28710-00004,전등공원,역사공원,NaN,인천광역시 강화군 길상면 온수리 산42,37.632824,126.4868582083,143607,NaN,NaN,NaN,NaN,NaN,1974-05-16,인천광역시 강화군청,032-930-3876,2019-09-20
2,28710-00005,내가공원,근린공원,NaN,인천광역시 강화군 내가면 고천리 산109-2,37.734243,126.422700,45000,NaN,NaN,NaN,NaN,NaN,1974-05-16,인천광역시 강화군청,032-930-3876,2019-09-20
3,28710-00007,유아공원,어린이공원,인천광역시 강화군 강화읍 동문안길 15,인천광역시 강화군 강화읍 관청리 486-1,37.7473662241,126.4866997714,1769,NaN,NaN,NaN,NaN,NaN,1979-04-20,인천광역시 강화군청,032-930-3876,2019-09-20
4,28710-00009,5호공원,어린이공원,NaN,인천광역시 강화군 강화읍 관청리 15,37.7520182546,126.489721,1773,NaN,NaN,NaN,NaN,NaN,1988-02-20,인천광역시 강화군청,032-930-3876,2019-09-20

In [72]:
park.columns

Index(['관리번호', '공원명', '공원구분', '소재지도로명주소', '소재지지번주소', '위도', '경도', '공원면적',
       '공원보유시설(운동시설)', '공원보유시설(유희시설)', '공원보유시설(편익시설)', '공원보유시설(교양시설)',
       '공원보유시설(기타시설)', '지정고시일', '관리기관명', '전화번호', '데이터기준일자'],
      dtype='object')

In [73]:
park1 = park.loc[:, ['공원명','소재지도로명주소']]
park1

      공원명               소재지도로명주소
0    관청공원                    NaN
1    전등공원                    NaN
2    내가공원                    NaN
3    유아공원  인천광역시 강화군 강화읍 동문안길 15
4    5호공원                    NaN
..    ...                    ...
639    7호                    NaN
640    8호                    NaN
641    1호                    NaN
642    1호                    NaN
643    2호                    NaN

[644 rows x 2 columns]

In [74]:
park2 = park1.fillna(0)

In [75]:
park3 = park2[park2.소재지도로명주소 != 0]
park3

       공원명                      소재지도로명주소
3     유아공원         인천광역시 강화군 강화읍 동문안길 15
5     6호공원      인천광역시 강화군 강화읍 남문로31번길 11
7     남산공원  인천광역시 강화군 강화읍 청하동길36번길 29-25
8      공원명                      소재지도로명주소
9    하마리공원    인천광역시 계양구 주부토로388번길 7(작전동)
..     ...                           ...
566    공원명                      소재지도로명주소
567   자유공원            인천광역시 중구 자유공원남로 25
568   율목공원                인천광역시 중구 율목로45
577  유수지공원     인천광역시 중구 신도시북로 31-35(운서동)
578  영마루공원         인천광역시 중구 영종대로 77(운서동)

[244 rows x 2 columns]

In [76]:
park3 = park3[park3.공원명 != '공원명']
park3

       공원명                      소재지도로명주소
3     유아공원         인천광역시 강화군 강화읍 동문안길 15
5     6호공원      인천광역시 강화군 강화읍 남문로31번길 11
7     남산공원  인천광역시 강화군 강화읍 청하동길36번길 29-25
9    하마리공원    인천광역시 계양구 주부토로388번길 7(작전동)
11   용종5공원        인천광역시 계양구 용마루1길 2(용종동)
..     ...                           ...
461  까투렴공원             인천광역시 서구 첨단동로 344
567   자유공원            인천광역시 중구 자유공원남로 25
568   율목공원                인천광역시 중구 율목로45
577  유수지공원     인천광역시 중구 신도시북로 31-35(운서동)
578  영마루공원         인천광역시 중구 영종대로 77(운서동)

[236 rows x 2 columns]

In [77]:
small_addr = list()

addr = park3.loc[:, ['소재지도로명주소']].values 
for tmp in addr :
    small_addr.append(tmp[0].split(" ")[1])

print(small_addr)

['강화군', '강화군', '강화군', '계양구', '계양구', '계양구', '계양구', '계양구', '계양구', '계양구', '계양구', '계양구', '계양구', '계양구', '계양구', '계양구', '계양구', '계양구', '계양구', '계양구', '계양구', '계양구', '계양구', '계양구', '계양구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '남동구', '동구', '동구', '동구', '동구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '미추홀구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '서구', '중구', '중구', '중구', '중구']

In [78]:
park3['GUGUN'] = small_addr
park3

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

       공원명                      소재지도로명주소 GUGUN
3     유아공원         인천광역시 강화군 강화읍 동문안길 15   강화군
5     6호공원      인천광역시 강화군 강화읍 남문로31번길 11   강화군
7     남산공원  인천광역시 강화군 강화읍 청하동길36번길 29-25   강화군
9    하마리공원    인천광역시 계양구 주부토로388번길 7(작전동)   계양구
11   용종5공원        인천광역시 계양구 용마루1길 2(용종동)   계양구
..     ...                           ...   ...
461  까투렴공원             인천광역시 서구 첨단동로 344    서구
567   자유공원            인천광역시 중구 자유공원남로 25    중구
568   율목공원                인천광역시 중구 율목로45    중구
577  유수지공원     인천광역시 중구 신도시북로 31-35(운서동)    중구
578  영마루공원         인천광역시 중구 영종대로 77(운서동)    중구

[236 rows x 3 columns]

In [79]:
park3.drop(['소재지도로명주소'], axis='columns', inplace=True)

In [80]:
park4 = park3.groupby('GUGUN').count()

In [81]:
park5 = park4.rename(columns={'공원명':'공원수'})
park5

       공원수
GUGUN
강화군      3
계양구     22
남동구     49
동구       4
미추홀구    45
서구     109
중구       4

In [84]:
park5.to_csv('./csv/2_INCHEON/jiyoon/incheon_gugun_park.csv', encoding='euc-kr')

In [83]:
park5

       공원수
GUGUN
강화군      3
계양구     22
남동구     49
동구       4
미추홀구    45
서구     109
중구       4